### ISSUE TITLE
Update amount spent of claim after deleting expense while on the same activity

### ISSUE THREAD

**Issue by oleynikovo** [RostarSynergistics/ShinyExpenseTracker#102]
Guess we need to update Expense Totals of claim after deleting one of the claim's expenses. As it is now, the value is only updated after refresh. I'm not adequate enough to do it now, so I just open it for tomorrow

**Comment by ItsTristan** [comment]
This is a bug with ExpenseTotalsAdapter not receiving an update. The fragment is getting refreshed correctly if you go to the destinations tab and then back to the main summary.

Steps to Replicate:
1. Create a claim
2. Add an expense
3. Delete the expense
4. Swipe back to the summary without going back or viewing destinations. The total will still be there.
