### ISSUE TITLE
View List of Expense Items

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#13]
**Use Case Name:** Display an Expense Item list.
**Actors:** Claimant
**Goal:** To successfully list expense item(s)
**Trigger:** Claimant clicks on Expense List tab in Claim summary screen
**Preconditions:** Claimant has already added a claim, Claimant has already added at least one expense item
**Postconditions:** The expense Item is successfully Listed

**Basic Flow:**
1. The system displays in order of entry, the date the expense was incurred, the category, the textual description, amount spent, unit of currency, whether there is a photographic receipt, and incompleteness indicator.

**Exceptions:**
None

**Covers:** US05.01.01

**Comment by adamjford** [comment]
Estimate: 4
