### ISSUE TITLE
Delete an Expense Item

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#14]
**Actors:** Claimant
**Goal:** To successfully delete expense item(s). 
**Trigger:** User holds holds down the respective expense item on the list view
**Preconditions:** Claimant has already added a claim, Claimant has already added at least one expense item
**Postconditions:** The expense Item is successfully deleted

**Basic Flow:**
1. Claimant long presses the respective expense item on the list view
2. A menu displays an option to delete the expense item
3. User presses "Delete" and the expense item is successfully deleted

**Exceptions:**
None

**Covers:** US04.07.01

**Comment by adamjford** [comment]
Estimate: 2
