### ISSUE TITLE
Edit an Expense Item

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#15]
**Actors:** Claimant
**Goal:** To successfully edit an expense item. 
**Trigger:** User holds holds down the respective expense item on the list view
**Preconditions:** Claimant has already added a claim, Claimant has already added at least one expense item.  Claimant is on the Expense List summary screen
**Postconditions:** The expense Item is successfully edited

**Basic Flow:**
1. User selects respective expense item on the list view
2. System displays Expense Summary screen for the respective expense
3. User edits the values of the respective expense item
4. User presses checkmark and the expense item is successfully edited
5. System returns to expense item summary screen

**Exceptions:**
None

**Covers:** US04.06.01

**Comment by adamjford** [comment]
Estimate: 3

**Comment by ItsTristan** [comment]
"holds down" -> inconsistent with storyboard; will need to update.
