### ISSUE TITLE
View Expense Item details

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#16]
**Actors:** Claimant
**Goal:** To successfully view an expense item and its details
**Trigger:** claimant clicks on an expense item in the list view
**Preconditions:** Claimant has already added a claim, Claimant has already added at least one expense item, claimant is on the expense item list activity.
**Postconditions:** The expense Item and its details are successfully listed

**Basic Flow:**
1. User clicks on respective expense list view item. 
2. The system displays the date the expense was incurred, the category, the textual description, amount spent, unit of currency, whether there is a photographic receipt, and incompleteness indicator.

**Exceptions:** None

**Covers:** US04.05.01

**Comment by adamjford** [comment]
Estimate: 4
