### ISSUE TITLE
Seg Faulting!

### ISSUE THREAD

**Issue by ItsTristan** [RostarSynergistics/ShinyExpenseTracker#168]
I'm getting legit seg faults when I try to open the ExpenseItemDetailActivity. I think it has something to do with the way saving and loading works.

Steps to replicate:
1. Add a claim
2. Add an expense
3. Attach a photo
4. Close the app
5. Clear the app from history (double boxes, swipe the activity away0
6. Reopen the app
7. Open the claim
8. Try to open the expense

`Fatal signal 11 (SIGSEGV) at 0xb850a6b0 (code=1), thread 3902 (yexpensetracker)`

**Comment by adamjford** [comment]
I'll look into this tomorrow.
