### ISSUE TITLE
Create an Expense Claim

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#17]
**Actors:** Claimant
**Goal:** A new Expense Claim is created
**Trigger:** Claimant presses the Plus button on the Expense Tracker screen
**Preconditions:** Claimant knows details about Claim to create
**Postconditions:** On success, opens up Claim Summary screen for new Expense Claim

**Basic Flow:**
1. Claimant presses the Plus button on the Expense Tracker screen
2. System displays a form to input data for a claim
3. Claimant enters name of Claim, start date, and end date
4. Claimant presses Checkmark button
5. System saves the claim
6. System displays the Claim Summary screen 

**Exceptions:**
4. Claimant enters invalid name, start date, or end date
4.1) Displays message detailing error with proper format
4.2) Claimant presses “OK” button
4.3) System returns to step 3

**Covers:** US01.01.01, US01.06.01

**Comment by adamjford** [comment]
Estimate: 4
