### ISSUE TITLE
Add destinations to an Expense Claim

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#18]
**Actors:** Claimant
**Goal:** Destinations are added to a claim
**Trigger:** Claimant selects the Add Destination item in the pop-up menu of the Plus button on the Claim Summary screen
**Preconditions:** Claimant knows details about destination(s) to add
**Postconditions:** On success, display a list of destinations associated with the claim

**Basic Flow:**
1. Claimant selects the Add Destination item in the pop-up menu of the Plus button on the Claim Summary screen
2. System displays a form to input destination info
3. Claimant enters destination name and reason for destination
4. Claimant presses Checkmark button
5. System updates and saves the chosen Claim with the new destination information 
6. System returns Claimant to the Claim Summary screen

**Exceptions:**
4. Claimant enters invalid destination name, or reason for destination
4.1) Displays message detailing error with proper format
4.2) Claimant presses “OK” button
4.3) System returns to step 3

**Covers:** US01.02.01, US01.06.01

**Comment by adamjford** [comment]
Estimate: 3
