### ISSUE TITLE
View an Expense Claim and its details

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#19]
**Actors:** Claimant
**Goal:** Display an expense claim and its details
**Trigger:** Claimant presses on the Claim in the list of the saved claims
**Preconditions:** A claim to display exists in the system
**Postconditions:** On success, display an expense claim and its details

**Basic Flow:**
1. Claimant chooses claim by tapping on it in the list of claims on the Expense Tracker screen 
2. System displays info on the claim selected and the Plus button that allows to add an Expense Item, a Destination or a Tag
3. If Claimant presses Back button, system displays the Expense Tracker screen to view existing claims or add a new claim

**Exceptions:** 

**Covers:** US01.03.01

**Comment by adamjford** [comment]
Estimate: 4
