### ISSUE TITLE
Edit an Expense Claim and its details

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#20]
**Actors:** Claimant
**Goal:** An expense claim and its details is edited
**Trigger:** Claimant chooses the Edit Claim item in menu
**Preconditions:** A claim to edit exists in the system
**Postconditions:** On success, an expense claim and its details is changed and has been saved

**Basic Flow:**
1. Claimant presses the Edit Claim menu item in Settings while on the Claim Summary screen 
2. System loads data from the claim in forms
3. Claimant edits the information
4. Claimant presses the Checkmark button
5. System updates and saves the Claim
6. System returns Claimant to the Claim Summary screen

**Exceptions:**
4.) Claimant entered invalid information 
4.1) System displays a message telling the Claimant of the invalid information
4.2) System returns to 2, not saving the edited information

**Covers:** US01.04.01, US01.06.01

**Comment by adamjford** [comment]
Estimate: 3

**Comment by saemorris** [comment]
The exceptions on this use case were wrong, I have fixed them
