### ISSUE TITLE
Delete an Expense Claim and its details

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#21]
**Actors:** Claimant
**Goal:** An expense claim and its details is deleted
**Trigger:** Claimant long presses the desired Claim in menu list of Claims on the Expense Tracker screen
**Preconditions:** A claim to delete exists in the system
**Postconditions:** On success, an expense claim and its details is deleted

**Basic Flow:**
1. Claimant long presses the desired Claim in menu list of Claims on the Expense Tracker screen
2. System asks for confirmation from the Claimant
3. Claimant presses OK
4. System deletes the Claim data
5. System returns to the Expense Tracker screen

**Exceptions:**

**Covers:** US01.05.01, US01.06.01

**Comment by adamjford** [comment]
Estimate: 2

**Comment by ItsTristan** [comment]
Blocked: Needs to be deleted from saved locations.

**Comment by adamjford** [comment]
Move to Project Part 5.
