### ISSUE TITLE
View a list of Expense Claims

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#22]
**Actors:** Claimant
**Goal:** Display a list of expense claims and their details in reverse chronological order with respect to starting date
**Trigger:** Claimant navigates to the Claim-List screen
**Preconditions:** Claims to display exist in the system
**Postconditions:** On success, display a list of expense claims and their details in reverse  chronological order with respect to starting date

**Basic Flow:**
1. Claimant navigates to the Claim-List screen
2. System displays a list of all claims, sorted in reverse chronological order by start date, with its associated start date, destinations of travel, status, tags, and currency totals.

**Exceptions:**

**Covers:** US02.01.01, US02.02.01

**Comment by adamjford** [comment]
Estimate: 5
