### ISSUE TITLE
Assign Expense Claim to a tag

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#23]
**Actors:** Claimant
**Goal:** an expense claim is given one or more alphanumeric tags
**Trigger:** Claimant presses the “Add Tag” button
**Precondition:** Claimant wants to add a tag to an expense claim
**Postcondition:** And expense claim has a tag associated with it

**Basic Flow:**
1. Claimant presses “Add Tag” button while viewing an expenses claim
2. System displays the “Add Tag” screen with a drop down view of existing claims to choose from
3. Claimant chooses a tag
4. Claimant presses add tag button
5. System assigns tag to claim
6. System returns to view claim page

**Exceptions:**

**Covers:** US03.01.01

**Comment by adamjford** [comment]
Estimate: 4
