### ISSUE TITLE
Manage Tags

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#24]
**Actors:** Claimant
**Goal:** View all existing claims
**Trigger:** Claimant presses the “Manage Claims” menu item
**Precondition:** Claimant wants to see existing tags
**Postcondition:** Claimant is presented with a list of all tags

**Basic Flow:**
1. Claimant selects the “manage tags” menu item
2. System displays a list of all existing tags
**Includes:** Add tag, Remove tag, Edit tag

**Exceptions:**

**Covers:** US03.02.01

**Comment by adamjford** [comment]
Estimate: 3
