### ISSUE TITLE
Add Tag

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#25]
**Actors:** Claimant:
**Goal:** Add a tag to the system
**Trigger:** Claimant presses the floating button
**Precondition:** Claimant is on the “Manage Tags” screen
**Postcondition:** Tag has been added to the system

**Basic Flow:**
1. Claimant presses the floating button
2. System displays a screen to add a new tag
3. Claimants adds a claim and presses the checkmark
4. System displays manage tags screen with the new tag added to the list

**Exceptions:**
3. Claimant enters a non-alphanumeric tag
	3.1) System displays “Invalid Tag”
	3.2) System returns to 2

**Extends:** Manage Tags

**Covers:** US03.02.01

**Comment by adamjford** [comment]
Estimate: 3

**Comment by ItsTristan** [comment]
Merged by #65
