### ISSUE TITLE
Remove Tag

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#26]
**Actors:** Claimant
**Goal:** Remove tag from the system
**Trigger:** Claimant long presses the tag they wish to remove
**Precondition:** Claimant is on “Manage Tags” screen
**Postcondition:** Tag has been removed from the system

**Basic Flow:**
1. Claimant long presses the tag that they wish to remove
2. System displays a dialog box to ask the claimant if they truly wish to remove the tag
3. Claimant selects 'Delete' from dialog box
4. System removes tag from the system
5. System reloads tag list

**Extends:** Manage Tags

**Exceptions:**

**Covers:** US03.02.01

**Comment by adamjford** [comment]
Estimate: 4

**Comment by RowdyRajan** [comment]
Blocked: depends on 25

**Comment by ItsTristan** [comment]
Still blocked: depends on #24
