### ISSUE TITLE
Edit Tag

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#27]
**Actors:** Claimant
**Goal:** Edit a tag name
**Trigger:** Claimant selects a tag to edit
**Precondition:** Claimant is on “Manage Tags” screen
**Postcondition:** Tag has been modified

**Basic Flow:**
1. Claimant selects a tag to edit
2. System displays an edit tag screen
3. Claimant edits the tag and presses the checkmark button
4. System returns to manage tags screen

**Extends:** Manage Tags

**Exceptions:**

**Covers:** US03.02.01

**Comment by adamjford** [comment]
Estimate: 3

**Comment by RowdyRajan** [comment]
Blocked: depends on 25

**Comment by ItsTristan** [comment]
still blocked: depends on #24
