### ISSUE TITLE
Attach a Photographic receipt to an Expense Item

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#29]
**Use Case Name:** Add an receipt photo to an expense item
**Actors:** Claimant
**Goal:** Add a photo of a receipt to an editable expense item
**Trigger:** Claimant presses the Add Photo button in the expense item view 
**Preconditions:** An editable expense item exists. The claimant is viewing the expense item they wish to add a photo to.
**Postconditions:** On success a photo is added to the selected expense item and the claimant is taken back to the expense item view. The photo is also less than 65536 bytes in size

**Basic Flow:**
1. Claimant presses the Add Photo button
2. System control is passed to a camera app
3. The claimant takes a photo
4. The photo taken is saved to memory
5. System control is passed back to the expense tracker app
6. The photo taken is loaded from memory
7. The photo taken is displayed
8. The photo is added to the expense item
9. The user is taken back to the expense item view 

**Exceptions:**
3. Claimant cancels the camera app
	3.1) The claimant is taken back to the expense item view
6. The photo is larger than 65536 bytes
	6.1) The photo is scaled down
	6.2) The scaled down photo is saved to memory and used as the receipt photo
	6.3) The old photo is deleted from memory

**Covers:** US06.01.01, US06.04.01

**Comment by adamjford** [comment]
Estimate: 7
