### ISSUE TITLE
View Photographic Receipt

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#30]
**Actors:** User
**Goal:** View a receipt photo associated with an expense item
**Trigger:** User presses the photo thumbnail button in an expense item view
**Preconditions:**  The expense item must have a receipt photo associated with it. The user is viewing the expense item with the receipt they wish to view.
**Postconditions:** The receipt photo is displayed
 
**Basic Flow:**
1. User presses the thumbnail of the photo in an expense item view
2. System displays the receipt photo
 
**Exceptions:**
1.There is no receipt picture associated with the current expense item
1.1) System displays message stating that there is no receipt photo for the current expense item
1.2) The claimant is returned to the expense item view

**Covers:** US06.02.01, US08.05.01

**Comment by adamjford** [comment]
Estimate: 4
