### ISSUE TITLE
 Submit an Expense Claim for Approval

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#31]
**Actors:** Claimant
**Goal:** A claim is submitted for approval
**Trigger:** Claimant presses the “Submit Claim” button in the View Expense Claim screen
**Preconditions:** A claim has already been made. The claimant is viewing the View Expense Claim screen. The claim has not already been submitted for approval
**Postconditions:** On success, the claim has 'submitted' status and no further changes are allowed to the claim (except for tags)

**Basic Flow:**
1. Claimant presses the Submit Claim button in the View Expense Claim screen
2. System asks to confirm the submission
3. Claimant presses the OK button
4. System submits the claim to a database to be approved
5. System marks the claim as Submitted

**Exceptions:**
1. The claim being submitted is incomplete
1.1) System displays an error and asks the Claimant to correct the issues
1.2) Claimant presses OK
1.3) System returns to the View Expense Claim screen

**Covers:** US07.01.01, US07.02.01

**Comment by adamjford** [comment]
Estimate: 5

**Comment by saemorris** [comment]
Do we still want the "submit claim" button or would a menu item be better? I'm thinking that a menu item would help keep the claim summary screen neater and less cluttered.  

Thoughts?
