### ISSUE TITLE
ElasticSearch: Push an Expense Claim Online

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#34]
**Actors:** Claimant
**Goal:** Sync expense claims changed offline with the online version
**Trigger:** Connection to the internet
**Precondition:** Claimant isn't connected to the internet
**Postcondition:** Offline changes made by Claimant are pushed online

**Basic Flow:**
1. System is not connected to the internet
2. Claimant makes a change/creates a new claim/expense item
3. System saves changes locally
4. System is connected to the internet
5. System pushes changes online

**Exceptions:** 

**Covers:** US09.01.01

**Comment by adamjford** [comment]
Estimate: 10

**Comment by RowdyRajan** [comment]
Make sure that when this is implemented the tests relating to the method saveExpenseClaim in ExpenseClaimController also pass
