### ISSUE TITLE
Project Part 3

### ISSUE THREAD

**Issue by adamjford** [RostarSynergistics/ShinyExpenseTracker#41]
How are we going to do this?

I figure the fastest way to get this done is for most/all of us to get together in a room for an afternoon/evening and get it all done. However, it would be way easier if we used software that would allow multiple people to work in a single document at once. Does such UML software exist? Does Google Docs have a Visio equivalent?

If not, I suppose we could have people work on segments of the class diagram on their own, and then standardize and combine them at the end.

**Comment by ItsTristan** [comment]
I'm in favour of doing a meetup, so long as we can organize a date and time.

As for software, I think Google Drawings is their Visio equivalent. I don't remember it being very good, but I think it should be good enough to get the layout done before we move it to better format.

**Comment by saemorris** [comment]
I won't be back in town until late on the 22nd.  But I can do a section of the UML or convert it into a better format if you guys get it done.

**Comment by ramish94** [comment]
I agree with Adam and Tristan. We should all meet up one day and finish it. Shouldn't take too long.

**Comment by adamjford** [comment]
Friday doesn't work for me at all, and I've already got a meeting with a different group this evening. So Saturday or Sunday?

**Comment by ramish94** [comment]
I'm fine to meet Sunday, but it'd have to be in the morning

**Comment by adamjford** [comment]
We should start in the morning on either day, as I'm not exactly sure how long this'll take. The more leeway we give ourselves, the better.

**Comment by RowdyRajan** [comment]
I'm good to meet either day

**Comment by adamjford** [comment]
Me too, of course. I think that if at least 3-4 of us can meet on Saturday, that'll be ideal as that'll give us time on Sunday too if we need it.

**Comment by ItsTristan** [comment]
I won't be able to do tomorrow morning but Sunday morning is fine.

**Comment by ramish94** [comment]
Yeah, I can do Sunday morning

**Comment by adamjford** [comment]
I assume that means we'll have the most on Sunday so let's do that! Meet up
at 10 AM? Could someone book a breakout room for as long as possible?

**Comment by ramish94** [comment]
CSC 2-50 booked from 10am-4pm.

Not sure how long you wanted, but since it's a Sunday, I don't think we'll
have much trouble staying over the booked time if needed.

See you all then.

**Comment by adamjford** [comment]
Probably going to be a little late, depending on the LRT. I'll bring
Timbits to make up for it.

**Comment by ItsTristan** [comment]
No rush because apparently CSC is locked right now. Surprise!

**Comment by adamjford** [comment]
Ah shit, I forgot about that. CSC doesn't unlock until noon...

**Comment by adamjford** [comment]
Let's meet in CAB until CSC unlocks. It's probably pretty empty.

**Comment by ramish94** [comment]
Hah. I'll be a little late as well. Meet in cab in the meanwhile?

**Comment by oleynikovo** [comment]
You just have to swipe your OneCard to unlock the doors

**Comment by ramish94** [comment]
Everyone come to CAB basement. Me and Tristan are already settled there, so we can go from there.

**Comment by adamjford** [comment]
Home stretch for this today! I started making some changes last night based
on Alex's feedback on draw.io, but there's more to do, including:

* Making sure every Activity implements IView<> and has the proper model
type binded (see his email for info on how to do this)
* Last thing to do: make sure both end of every relationship has proper
arities (1, 0..*, etc)

I'm probably forgetting some stuff, but hopefully a few of us can get in
there and finish this off!

By the way, Sarah, if you want in on editing this, go to draw.io, choose
Google Drive, Open Existing, then find the drawing in our project folder.

**Comment by ramish94** [comment]
If anyone wants to work with us on finishing Project Part 3, we have
CSC2-18 booked for an hour.

**Comment by adamjford** [comment]
I'm at home working on my day job, but I'm going to take a peek around 3 on
my own. I can polish the whole thing up.

**Comment by ramish94** [comment]
Alright, sounds good.

**Comment by ItsTristan** [comment]
**No more edits to the Google Doc** (sorry Alex!). Sarah is moving it to Dia so that the arrow nightmare can finally come to an end.

**Comment by adamjford** [comment]
Fair enough!

**Comment by adamjford** [comment]
Took a peek at the latest version of the class diagram in GitHub, and it looks like the Activities don't have a IModel implementer bound to them, like in this example: http://etutorials.org/Programming/UML/Chapter+6.+Class+Diagrams+Advanced+Concepts/Parameterized+Class/

**Comment by ItsTristan** [comment]
[Project Part 3 Feedback](https://eclass.srv.ualberta.ca/mod/feedback/view.php?id=1411156) is due March 2 at 11:55 pm.

**Comment by adamjford** [comment]
Done!
