### ISSUE TITLE
Create ExpenseClaimsController

### ISSUE THREAD

**Issue by adamjford** [RostarSynergistics/ShinyExpenseTracker#47]
(Depends on #46)

**Comment by RowdyRajan** [comment]
Blocked: Need WebServiceExporter to fully implement. Purpose of this class is also unclear

**Comment by ItsTristan** [comment]
All WebServiceExporter does is save the claim to elastic search. Your code only needs to pass tests--it doesn't actually need to save right now (we can weave it together once we know all the parts pass their tests).

Can you create a mock object for WebServiceExporter and continue working?
