### ISSUE TITLE
Create an Expense Item

### ISSUE THREAD

**Issue by ramish94** [RostarSynergistics/ShinyExpenseTracker#5]
**Actors:** Claimant
**Goal:** A new Expense Item is created
**Trigger:** Claimant presses the Add Expense Item Button
**Preconditions:** Claimant has already added a claim, Claimant knows the details of the Expense Item he wants to make
**Postconditions:** On success, opens up Expense Item View screen for new Expense Item

**Basic Flow:**
1. Claimant chooses to add Expense Item. Either because of being prompted to after adding a claim, or manually pressing the "Add Expense Item" button on the Expense Item view. 
2. Claimant inputs the data required which consists of the date, textual description, category, amount spent, and unit of currency. 
3. Claimant has the option to flag the expense item and mark it as incomplete
4. Claimant presses the "Submit" button
5. Claimant has the option to either add another Expense Item, or be done. If they want to add another expense Item, they are bought back to Step #2. If not, they continue to #6
6. Claimant is taken to an Expense Item View screen where all their expense Items are visible. 

**Exceptions:**
4. Claimant enters invalid data
4.1) Displays message detailing error with proper format
4.2) Claimant presses “OK” button
4.3) System returns to step 2

**Covers:**  US04.01.01, US04.02.01, US04.03.01, US04.04.01, US04.08.01

**Comment by adamjford** [comment]
Estimate: 5
