### ISSUE TITLE
ExpenseClaimController

### ISSUE THREAD

**Issue by ItsTristan** [RostarSynergistics/ShinyExpenseTracker#52]
What is ExpenseClaimController? It isn't connected to anything in the UML except for ExpenseClaimList, and its composition/arity with ExpenseClaimList doesn't seem to agree with its method calls. Is it a controller for a single list or for many lists (as in multi-user(?))? Does it export data or does the model export data?

Its role isn't clear from the UML and #47 doesn't elaborate.

**Comment by adamjford** [comment]
In MVC, controllers mediate between models and views, handling events and user input. So, for example, when a user interacts with the UI in such a way that would change the model, the UI calls the appropriate method on the controller, which changes the model, which then changes any views it's attached to.

Here's an example controller (from the FillerCreep app): https://github.com/abramhindle/FillerCreepForAndroid/blob/master/src/es/softwareprocess/fillercreep/GameController.java

**Comment by ItsTristan** [comment]
Sure and I get that part. The Controller (`ExpenseClaimController`) manages the model (`ExpenseClaimList`) which is an aggregation of ExpenseClaim objects.
What's confusing is that what we have in the [UML](https://github.com/RostarSynergistics/ShinyExpenseTracker/wiki/Class-Diagram) right now is unclear.
* Why does `addExpenseClaimToList` accept an `ExpenseClaimList` as an argument and not an `ExpenseClaim` itself?
* Why does the `ExpenseClaimList` Model talk directly to the `Exporter` and not the `Controller`?
* Why is 0..* `ExpenseClaimList`'s composed of exactly 1 controller?
* Why can you get an `ArrayList<ExpenseClaim>` from the Controller? When would you need to do that?

It's probably a simple thing but it was the only part that didn't make any sense at all when I was writing the skeletons. Either I'm very confused or the way we're modeling this is wrong.

**Comment by adamjford** [comment]
Ah, sorry. The UML is probably just wrong.
