### ISSUE TITLE
Difference between ExpenseClaimRepository and ExpenseClaimList?

### ISSUE THREAD

**Issue by ItsTristan** [RostarSynergistics/ShinyExpenseTracker#57]
From what I can see, Repository is a singleton that returns new, distinct instances of ClaimList objects whenever they're loaded from a file. Is there a case when we would want to have multiple copies of a ClaimList floating around? Or can these be merged into one singleton object that manages all claims in one global list?

**Comment by adamjford** [comment]
Currently, the Repository only handles the saving and loading of the List from a file (well, currently SharedPreferences, but will be file eventually).

Although, now that I think about it, we have an Exporter in the UML. Isn't that supposed to do that?

**Comment by ItsTristan** [comment]
Yeah, we kind of have multiple classes that want to be able to save and load claims. The way I pictured it was we would create a new Exporter object that will do the actual saving part, and all we have to do is give that object to whoever's in charge of saving. That way, the Exporter object can be a "ToFile" exporter or "ToElasticSearch" etc. without changing who or how we use it.
