### ISSUE TITLE
Project Part 4 - Outstanding Issues

### ISSUE THREAD

**Issue by ItsTristan** [RostarSynergistics/ShinyExpenseTracker#85]
The end of project part 4 is nearing. Once ~~#82~~, ~~#83~~ and ~#84~ are merged, we should have a basically functioning app, minus saving (#59 in progress).

Some non-feature things that still need to be done:
* [x] UML needs to be updated. (related: #75)
* [ ] Everything needs to have Javadocs
  * You need two *s, not just one: `/** My documents */`. Eclipse should fill in part of the data for you.
  * Javadocs will need to be compiled into the /doc/ folder.
  * If your function has `@Override`, you don't need a Javadoc for it. Unless your function does something particularly spectacular, that information is elsewhere
  * Bonus points if you can find a way to make inherited API comments show up in the Javadoc.
* [x] I know I left `FIXME`s everywhere but if there are still any lingering around, they need to be cleaned up.
  * If you've fixed it, delete it.
  * If they point to the UML, make a note of the change and delete it.
  * If you're not sure, make an issue and delete it.
* [x] Coding conventions need to be followed
  * I think everyone's been pretty good about this, with only minor quirks here and there.
  * If you're not putting comments in your code, I recommend putting whitespace to make logical groupings: it's a lot easier to read.
  * Check our [official-unofficial coding conventions](https://github.com/RostarSynergistics/ShinyExpenseTracker/wiki/Coding-Conventions) page as well as the [official google-java coding style](https://google-styleguide.googlecode.com/svn/trunk/javaguide.html). If our page is missing something important be sure to add it.
* [x] Clean up unused imports.
  * Almost all of our warnings are unused imports and variables. 
  * Press Ctrl+Shift+O to have eclipse clean up imports for you automatically.
  * If you're really lazy, you can have eclipse do all of this for you: Window > Preferences > Java > Clean Up. Create a new profile and tell it to clean up whatever you want.

**Comment by adamjford** [comment]
I'm going to bed because I'm utterly braindead, but it looks like I'll be skipping my usual work shift tomorrow to continue working on this after my 9-10 class up until 4. Anyone want to meet up if/when available?

**Comment by ItsTristan** [comment]
Fair enough, good sir. I think I'll be missing a bunch of my classes, except maybe 301 (from 9-10), just in case Hindle extends the deadline to 4 pm AoE again. Otherwise I'm completely sadistic and happy to meet up to do even more work.

**Comment by adamjford** [comment]
I've booked CSC 2-50 from 10-2. Couldn't get it from any longer than that. Looks like every breakout room is booked between 2 and 4. :(
