### ISSUE TITLE
Expense Item View Details

### ISSUE THREAD

**Issue by oleynikovo** [RostarSynergistics/ShinyExpenseTracker#97]
I just noticed issues #16 and #15 are started in the exact same way (i.e. select an expense from the expense list view). In the ExpenseItemFragment, clicking on an expense in the list will launch an editing activity. So I wonder, what is the best way to make both issues co-exist

**Comment by oleynikovo** [comment]
Ok, I just decided to do a pop-up promt, like the one when deleting the expense, but with different text. If anyone has problem with that, just reopen the issue

**Comment by ItsTristan** [comment]
I think a context menu like that would be a bit inconsistent with the rest of the app. It might warrant some further discussion for fixing the overall flow of our program later on.

For now, can you make the fragment open the expense item info first, and then have an "Edit Expense" button in the settings menu at the top right open it for editing?
